### ISSUE TITLE
【添加引擎】

### ISSUE THREAD

**Issue by 990721830** [dengyuhan/magnetW#1]
这几个BT站是最好的
http://cntorrentkitty.com/tk/%s/1-0-0.html
https://zh.btdb.to/q/%s
https://cn.bt4g.com/search/%s

bt.xiandan.in
而且你这个网站没有关键字可以替换%s
我应该如何添加到浏览器自定义引擎
还有能不能做一个不是磁力的聚合引擎
这是我写的你看一下能不能做到
https://www.jianshu.com/p/33f00a79e1e8

**Comment by dengyuhan** [comment]
这些站后续会看情况加入

暂不打算支持替换关键词，但你可以修改源码自行搭建

**Comment by 990721830** [comment]
我可是小白......
啥也不会.......
