### ISSUE TITLE
json文件读入中文乱码

### ISSUE THREAD

**Issue by Iwrbw** [dengyuhan/magnetW#11]

**Comment by dengyuhan** [comment]
Windows的吗，用Windows的编辑器创建json文件试一下[#8](https://github.com/dengyuhan/magnetW/issues/8)

**Comment by Iwrbw** [comment]
测试了目前修改字符编码无效，不过我在代码里使用new String(rule.getSite, "utf-8")能转为正常中文，不过不能完全转换过来，如：种子搜 转为 种子？？，这个‘搜’转不过来。另外，IDEA修改字符集好像没有用。

**Comment by dengyuhan** [comment]
改这个文件的编码，用Notepad之类的编辑器

![image](https://user-images.githubusercontent.com/17588779/56482094-e2b7b980-64f4-11e9-85e2-9a547ddd97c9.png)

**Comment by Iwrbw** [comment]
这个方法有使用，无效的

**Comment by dengyuhan** [comment]
实在不行就先在json里URLEncoder，在java里URLDecoder

**Comment by Iwrbw** [comment]
在json里如何操作，不太明白。

**Comment by dengyuhan** [comment]
[在线URLEncode](http://tool.chinaz.com/Tools/urlencode.aspx)
#### Json
```
{
    "site": "%e7%a7%8d%e5%ad%90%e6%90%9c",
    "waiting": "0",
    "group": "//table[@class='table table-bordered table-striped']",
    "magnet": ".//a//@href",
    "name": ".//tbody//a",
    "size": ".//tbody//tr//td[2]//strong",
    "date": ".//tbody//tr//td[1]//strong",
    "url": "http://www.zhongzijun.com",
    "source": "http://www.zhongzijun.com/list/%s/%d",
    "source_size": "http://www.zhongzijun.com/list_length/%s/%d"
  }
```
#### Java
```
URLDecoder.decode(rule.getSite())
```

**Comment by Iwrbw** [comment]
这样确实是可以了。另外，这个项目需要梯子吗？

**Comment by dengyuhan** [comment]
要看源站是否需要梯子，比如种子搜就需要梯子才能访问

**Comment by Iwrbw** [comment]
难怪，我用你的测试是可以正常使用的。我本地连接失败。

**Comment by grainrain** [comment]
`public class GsonUtil {
    private static Gson gson = new Gson();

    public static <T> T fromJson(InputStream inputStream, TypeToken<T> token) {
        try {
            return gson.fromJson(new InputStreamReader(inputStream,"utf-8"), token.getType());
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
            return  null;
        }
    }
}`

GsonUtil 修改如上

**Comment by dengyuhan** [comment]
[2.0.0](https://github.com/dengyuhan/magnetW/releases/tag/2.0.0) 已修复
