### ISSUE TITLE
magnetW的URL路径造成运行出错

### ISSUE THREAD

**Issue by kukudemajia** [dengyuhan/magnetW#13]
版本：2.0.0
Tomcat/7.0.92
war文件直接上传部署在二级目录下，不是在根目录下，
比如http://192.168.0.12:7070/mag/
比如在./WEB-INF/views/index.jsp里面
` <link href="/resources/css/search_result.css" rel="stylesheet">`
就会造成实际引用地址变成了http://192.168.0.12:7070/resources/css/search_result.css
然后就报错，类似的问题存在好些地方，不止这一个文件

**Comment by dengyuhan** [comment]
升级新版

**Comment by kukudemajia** [comment]
非常棒
