### ISSUE TITLE
中文搜索词无法搜索，切换搜索时乱码

### ISSUE THREAD

**Issue by sjkgames** [dengyuhan/magnetW#20]
> 操作系统版本：
>Liunx Centos7.4x64
> 磁力搜版本：  
>2.0.5
> 问题描述：  
>中文搜索词搜索时，搜索不到任何内容，且在切换搜索引擎时中文变成乱码,宝塔面板内部署的Tomcat.磁力搜的版本是最新版本（2.0.5）
> 异常日志（如果有）：

**Comment by dengyuhan** [comment]
源站列表的显示也是乱码的吗

看一下规则加载日志是否正常
```
[INFO ]----[2019-06-04 13:33:29:760]----[in.xiandan.magnetw.service.MagnetRuleService.getMagnetRule(MagnetRuleService.java:156)]
[加载]--->种子搜 : https://www.zhongzilou.com
[加载]--->BT蚂蚁 : http://www.btaot.com
[加载]--->BT4G : https://cn.bt4g.com
[加载]--->Nyaa（动漫） : https://nyaa.si
[加载]--->Sukebei Nyaa : https://sukebei.nyaa.si
[加载]--->BTSOW : https://btsow.pw
[加载]--->Torrentz2 : https://www.torrentz2.eu
[加载]--->idope : https://idope.se
[加载]--->BTbook : https://btbookk.net
[加载]--->SkrBT : https://www.skrbt.world
[加载]--->磁力柠檬 : https://lemoncili.com
[加载]--->BT磁力链 : https://www.bturl.tv
[加载]--->MAG磁力站 : http://oabt005.com
13个网站规则加载完成，其中启用13个，忽略0个
```

**Comment by sjkgames** [comment]
[INFO ]----[2019-06-10 01:04:10:061]----[in.xiandan.magnetw.service.MagnetRuleService.getMagnetRule(MagnetRuleService.java:154)]
[加载]--->种子搜 : https://www.zhongzilou.com
[加载]--->BT兔子 : https://www.btrabbit.win
[加载]--->BT蚂蚁 : http://www.btaot.com
[忽略]--->BT4G : https://cn.bt4g.com
[加载]--->SkrBT : https://www.skrbt.world
[加载]--->Nyaa : https://nyaa.si
[加载]--->磁力天堂 : http://www.cilisky.com
[加载]--->MAG磁力站 : http://oabt005.com
[加载]--->磁力柠檬 : https://lemoncili.com
[加载]--->磁力猫 : https://www.cilimao.xyz
[加载]--->BT磁力链 : https://www.bturl.tv
11个网站规则加载完成，忽略1个


[INFO ]----[2019-06-10 01:04:10:073]----[in.xiandan.magnetw.service.MagnetRuleService.loadTrackers(MagnetRuleService.java:179)]
加载78个Tracker服务器







------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 凌晨1:02
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 中文搜索词无法搜索，切换搜索时乱码 (#20)




源站列表的显示也是乱码的吗
 
看一下规则加载日志是否正常
 [INFO ]----[2019-06-04 13:33:29:760]----[in.xiandan.magnetw.service.MagnetRuleService.getMagnetRule(MagnetRuleService.java:156)] [加载]--->种子搜 : https://www.zhongzilou.com [加载]--->BT蚂蚁 : http://www.btaot.com [加载]--->BT4G : https://cn.bt4g.com [加载]--->Nyaa（动漫） : https://nyaa.si [加载]--->Sukebei Nyaa : https://sukebei.nyaa.si [加载]--->BTSOW : https://btsow.pw [加载]--->Torrentz2 : https://www.torrentz2.eu [加载]--->idope : https://idope.se [加载]--->BTbook : https://btbookk.net [加载]--->SkrBT : https://www.skrbt.world [加载]--->磁力柠檬 : https://lemoncili.com [加载]--->BT磁力链 : https://www.bturl.tv [加载]--->MAG磁力站 : http://oabt005.com 13个网站规则加载完成，其中启用13个，忽略0个

**Comment by dengyuhan** [comment]
搜索的时候看下请求是否乱码
![image](https://user-images.githubusercontent.com/17588779/59162013-792f5100-8b1c-11e9-8545-a22f959dd1da.png)

**Comment by sjkgames** [comment]
请求的时候不乱码，但是搜索不到任何内容，在切换搜索引擎的时候，原本输入的内容就会乱码，




------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 凌晨1:10
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 中文搜索词无法搜索，切换搜索时乱码 (#20)




搜索的时候看下请求是否乱码

**Comment by dengyuhan** [comment]
你本地调试一下吧，如果本地正常了服务器还不行，那可能环境有问题

**Comment by sjkgames** [comment]
是否支持tomcat7



------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 凌晨1:18
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 中文搜索词无法搜索，切换搜索时乱码 (#20)




你本地调试一下吧，如果本地正常了服务器还不行，那可能环境有问题

**Comment by dengyuhan** [comment]
只用过tomcat8、9

7没有试过

**Comment by sjkgames** [comment]
问题解决，不支持tomcat7，切换至tomcat9问题解决；




------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 凌晨1:43
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 中文搜索词无法搜索，切换搜索时乱码 (#20)




只用过tomcat8、9
 
7没有试过

**Comment by sosel** [comment]
> 问题解决，不支持tomcat7，切换至tomcat9问题解决；
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "denghaha"<notifications@github.com>; 发送时间: 2019年6月10日(星期一) 凌晨1:43 收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [dengyuhan/magnetW] 中文搜索词无法搜索，切换搜索时乱码 (#20) 只用过tomcat8、9 7没有试过 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

我也遇到了，群晖里套件只有tomcat只有6和7版本，好尴尬
