### ISSUE TITLE
顺便写了个简易教程

### ISSUE THREAD

**Issue by hugoyue** [dengyuhan/magnetW#21]
> 操作系统版本：
>CentOS 6.x
> 磁力搜版本：  
>v2.0.5
> 问题描述：  
> 资源站磁力柠檬和BT磁力链接报错：HTTP error fetching URL

对作者表示感谢，磁力聚合搜索一定程度上提高用户查找资源的效率，顺便写了一个简易教程 https://www.moewah.com/archives/2112.html

**Comment by dengyuhan** [comment]
规则已更新

很好可以帮助到一些新手👏
