### ISSUE TITLE
是否可以添加一个手机自适应页面？

### ISSUE THREAD

**Issue by sjkgames** [dengyuhan/magnetW#23]
> 操作系统版本：
>ios/android
> 磁力搜版本：  
>2.0.5
> 问题描述：  
>是否可以添加一个自适应手机页面？现在手机默认匹配电脑页面，显示有一些问题
> 异常日志（如果有）：

**Comment by dengyuhan** [comment]
手机版不是有小程序吗

**Comment by sjkgames** [comment]
平常使用浏览器比较多，我看到index.jsp里面有自适应的代码，但是手机里显示无效，不清楚为什么




------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年6月23日(星期天) 晚上6:59
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "Trojan Knife"<376686131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 是否可以添加一个手机自适应页面？ (#23)




手机版不是有小程序吗

**Comment by dengyuhan** [comment]
网页暂时不打算适配手机
