### ISSUE TITLE
规则列表里面只有八个规则

### ISSUE THREAD

**Issue by 5536086** [dengyuhan/magnetW#26]
>操作系统版本：  centos7
>磁力搜版本：  2.0.6

#### 异常日志：
```

```

**Comment by dengyuhan** [comment]
[看文档](https://github.com/dengyuhan/magnetW/blob/master/Config.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE)

```
#是否忽略需要代理才能访问的源站
proxy.ignore=true
```

#### Log
>[INFO ]----[2019-07-03 13:55:39:630]----[in.xiandan.magnetw.service.MagnetRuleService.getMagnetRule(MagnetRuleService.java:156)]
>[加载]--->种子搜 : https://www.zhongzilou.com
>[**忽略**]--->BT蚂蚁 : http://www.btaot.com
>[**忽略**]--->BT4G : https://cn.bt4g.com
>[加载]--->Nyaa（动漫） : https://nyaa.si
>[**忽略**]--->Sukebei Nyaa : https://sukebei.nyaa.si
>[**忽略**]--->BTSOW : https://btsow.pw
>[加载]--->Torrentz2 : https://www.torrentz2.eu
>[**忽略**]--->idope : https://idope.se
>[加载]--->BTbook : https://btbookk.net
>[加载]--->SkrBT : https://www.skrbt.world
>[加载]--->磁力柠檬 : https://lemencili1.xyz
>[加载]--->卧槽搜搜 : http://www.wcs444.com
>[加载]--->MAG磁力站 : http://oabt005.com
>13个网站规则加载完成，其中启用8个，**忽略5个**

**Comment by 5536086** [comment]
多谢，解决了，但是“[忽略]--->BT蚂蚁 : http://www.btaot.com” 这个地址失效了，请更新
