### ISSUE TITLE
手机页面有问题

### ISSUE THREAD

**Issue by 5536086** [dengyuhan/magnetW#27]
>操作系统版本：  安卓9.0 手机浏览器
>磁力搜版本：  2.0.7

#### 异常日志：
```

```

**Comment by dengyuhan** [comment]
贴下截图和链接

**Comment by 5536086** [comment]
![Screenshot_20190719_110128_com quark browser](https://user-images.githubusercontent.com/20472307/61506496-de783b00-aa14-11e9-9771-a94551ce551b.jpg)
上面这个是 我的错误页面

![Screenshot_20190719_110149_com quark browser](https://user-images.githubusercontent.com/20472307/61506516-ed5eed80-aa14-11e9-976d-1222e1118d55.jpg)
上面这个是你的错误页面

**Comment by dengyuhan** [comment]
什么型号的，这是什么浏览器

出现404的链接是多少

**Comment by 5536086** [comment]
你的出错原因找到了，是被墙了，挂代理能访问你的，我的还是不行，手机夸克浏览器和谷歌浏览器都试了

**Comment by dengyuhan** [comment]
你用电脑调试手机页面，看控制台给的什么错

**Comment by 5536086** [comment]
电脑调试手机页面竟然不报错，能正常显示，我去，好奇葩奇怪
![TIM截图20190719111348](https://user-images.githubusercontent.com/20472307/61506924-5004b900-aa16-11e9-83c3-2e5d878c0d8b.png)

**Comment by dengyuhan** [comment]
有css没加载出来，可以清浏览器缓存试试

**Comment by 5536086** [comment]
但是需要的那些css文件好像不存在啊，用的是你编译好了的那个2.0.7的war文件，你看看里面是不是缺文件了

**Comment by dengyuhan** [comment]
war没有问题，你还是需要本地调试找出问题

**Comment by 5536086** [comment]
额，好吧，我再摸索摸索，用的宝塔，总是有点问题
