### ISSUE TITLE
请问一下，如设置端口号呢？

### ISSUE THREAD

**Issue by qingshanking** [dengyuhan/magnetW#30]
#### 问题描述：
请问一下，如何配置这个项目的端口号，我不想使用默认的80端口和localhost访问，请问这个需要怎么配置呢？

**Comment by dengyuhan** [comment]
[Tomcat的端口配置](https://blog.csdn.net/qq_40180411/article/details/82112344)

**Comment by qingshanking** [comment]
谢谢指导
