### ISSUE TITLE
请求源站超时

### ISSUE THREAD

**Issue by sdy0803** [dengyuhan/magnetW#33]
>操作系统版本：  macos mojave
>磁力搜版本：  2.1.0

#### 问题描述：
搜索了几个种子是正常的，但是过了一会儿 就显示请求源站超时 没法正常用了

#### 异常日志：
```

```

**Comment by dengyuhan** [comment]
先检查是否可以正常访问到源站
```
curl [源站地址]
```

超时一般是网的问题，以演示站为准，如果演示站能正常搜，说明这个源站还能用

可以尝试调大超时时间，或者开启代理

**Comment by sdy0803** [comment]
thx
