### ISSUE TITLE
搭配它，如虎添翼

### ISSUE THREAD

**Issue by Mr-xn** [dengyuhan/magnetW#34]
- 项目很棒！聚合磁力搜索。
- 搭配它：[cloud-torrent](https://github.com/jpillora/cloud-torrent) 下载，如虎添翼！

**Comment by liaijin** [comment]
cloud-torrent ，不稳定是咋回事呢

**Comment by Mr-xn** [comment]
> cloud-torrent ，不稳定是咋回事呢

@liaijin 感觉还是比较稳定，可以使用nginx反代

**Comment by liaijin** [comment]
@Mr-xn 服务器上用的nginx反代，和本地一样，一直在解析磁力。没搞明白

**Comment by Mr-xn** [comment]
> @Mr-xn 服务器上用的nginx反代，和本地一样，一直在解析磁力。没搞明白

@liaijin 有可能是你所在服务器网络问题或种子问题，用排除法试试
