### ISSUE TITLE
自己下载下来的war包部署和实例页面不符

### ISSUE THREAD

**Issue by clcaal** [dengyuhan/magnetW#35]
>操作系统版本：  linux7.0
>磁力搜版本：  v2.1.0

#### 问题描述：
部署后访问和示例页面不一样
实例页面有14个连接选项，而自己部署的只显示10个，并且在示例页面上能够搜索到资源，在自己搭的就找不到资源，而且自己搭建的默认为种子搜，实例默认为磁力王，当在自己搭建的上面点击磁力王后，页面刷新，输入要查询的东西，点击查询，又跳到了种子搜，这时候点击磁力王时，在搜索框内的汉字就变成了乱码，这个在实例页面上没有出现过

#### 异常日志：
```

```

**Comment by dengyuhan** [comment]
>实例页面有14个连接选项，而自己部署的只显示10个
[文档中](https://github.com/dengyuhan/magnetW/blob/master/Config.md)就是war的默认配置，也注明了每行配置的含义
```
#是否忽略需要代理才能访问的源站
proxy.ignore=true
```

>并且在示例页面上能够搜索到资源，在自己搭的就找不到资源
[其它说明](https://github.com/dengyuhan/magnetW/blob/master/Config.md#其它说明)已经讲过了，有些站是需要梯子才能访问的，要确保设备可以访问到源站，才能够正常使用

>而且自己搭建的默认为种子搜，实例默认为磁力王
要默认磁力王，修改如`rule.json`就可以，磁力王是最近新增的，而配置默认用的是github上的规则，我不能随便改默认的顺序，这会影响到其他人

>当在自己搭建的上面点击磁力王后，页面刷新，输入要查询的东西，点击查询，
从其它issues来看，乱码大多是环境问题，代码中已经`URLEncode`过，暂时没有更好的办法，目前只能靠自己调试

>又跳到了种子搜，这时候点击磁力王时，在搜索框内的汉字就变成了乱码
跳到种子搜猜测是乱码的原因，代码中是根据源站名称获取规则的，如果取不到就会取数组第一个，也就是种子搜

>这个在实例页面上没有出现过
开发的时候就用示例服务器调试的，示例页面当然不会有这些问题

**Comment by dengyuhan** [comment]
如果觉得默认配置不符合自己需要，可以[自定义](https://github.com/dengyuhan/magnetW/blob/master/Config.md)，不然这个配置文件就没意义了

**Comment by clcaal** [comment]
好的，明白



------------------ 原始邮件 ------------------
发件人: "denghaha"<notifications@github.com>; 
发送时间: 2019年8月11日(星期天) 下午5:50
收件人: "dengyuhan/magnetW"<magnetW@noreply.github.com>; 
抄送: "限量版丶农夫"<1350054584@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dengyuhan/magnetW] 自己下载下来的war包部署和实例页面不符 (#35)




如果觉得默认配置不符合自己需要，可以自定义，不然这个配置文件就没意义了
