### ISSUE TITLE
常见问题

### ISSUE THREAD

**Issue by dengyuhan** [dengyuhan/magnetW#36]
如果遇到乱码、超时等情况，可以查看[Wiki/常见问题](https://github.com/dengyuhan/magnetW/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by TheGayhub** [comment]
你好，没找到相关错误内容的处理情况？

**Comment by xiandanin** [comment]
这是旧版的文档了  暂时还没更新

**Comment by TheGayhub** [comment]
好吧
