### ISSUE TITLE
访问magnetw-2.1.0超时

### ISSUE THREAD

**Issue by LunaticTian** [dengyuhan/magnetW#39]
>操作系统版本：  docker tomcat8
>磁力搜版本：  2.1.0

#### 问题描述：
在相同环境下，访问自己的项目正常。但是无法访问magnetw-2.1.0，超时。

#### 异常日志：
```

```

**Comment by dengyuhan** [comment]
不太明白 截图看下

**Comment by LunaticTian** [comment]
已解决，谢谢！
搜索功能可以试试改进：点击搜索后尝试对其他BT站点查阅结果都会加载，能不能在点击搜索时同时爬取结果，不必再点击其他结果时再加载的情况！

**Comment by dengyuhan** [comment]
那样很不稳定，而且非常耗时，如果需要可以自己扩展一下

**Comment by LunaticTian** [comment]
可以尝试在爬取阶段进行处理，我尝试拓展一下。谢谢解答
