### ISSUE TITLE
mac版 无法启动

### ISSUE THREAD

**Issue by wildwolfzj** [dengyuhan/magnetW#40]
>操作系统版本：  mac 10.12.6
>磁力搜版本：  2.1.0

#### 问题描述：
下载了210版本，
本机java 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

#### 异常日志：
Tomcat started.
但浏览器，无论Safari，或是chrome都localhost，显示ERR_CONNECTION_REFUSED
不知道缺什么操作呢？

ss开或者关都试过了。貌似没有影响。

求助一下

**Comment by dengyuhan** [comment]
看看tomcat启动日志

**Comment by wildwolfzj** [comment]
[catalina.2019-08-13.log](https://github.com/dengyuhan/magnetW/files/3495797/catalina.2019-08-13.log)
15:23有个错误，不过我看不太懂，sorry，是缺少组建么

**Comment by dengyuhan** [comment]
`Caused by: java.net.SocketException: Permission denied`
没有权限 试试不放桌面  比如Downloads

**Comment by wildwolfzj** [comment]
[catalina.2019-08-13.log](https://github.com/dengyuhan/magnetW/files/3496236/catalina.2019-08-13.log)
多谢回复，刚刚放到download下，也开了整个目录的 chmod -R 777权限。但是还是老样子提示没权限。麻烦有空再帮忙看一下。

**Comment by dengyuhan** [comment]
试试换tomcat端口
