### ISSUE TITLE
首页的下来菜单怎么改？

### ISSUE THREAD

**Issue by eoqkraos** [dengyuhan/magnetW#47]
请问，首页的排序选项，/创建时间/文件胆小/下载人气...这个部分怎么改？
谢谢！

**Comment by dengyuhan** [comment]
[MagnetPageSiteSort](https://github.com/dengyuhan/magnetW/blob/master/src/main/java/in/xiandan/magnetw/response/MagnetPageSiteSort.java)中的常量对应[rule.json](https://github.com/dengyuhan/magnetW/blob/master/src/main/resources/rule.json)中的`paths`字段名，`sortName` 预设了对应的中文名称

[index.jsp#el-select ](https://github.com/dengyuhan/magnetW/blob/master/src/main/webapp/WEB-INF/views/index.jsp#L119)就是排序的组件
