### ISSUE TITLE
磁力链接规则

### ISSUE THREAD

**Issue by 8678askar** [dengyuhan/magnetW#5]
有些网站的磁力链接并不在href属性啊， 名字也并不在一个a里面    应该在改进一下    应该是给什么属性就找什么  而不是String nameHref = nameNote.getAttributes().getNamedItem("href").getTextContent();

**Comment by milaoguai** [comment]
把war文件解压后，在windows上的jsp大师环境下，显示几个磁力链接站点名字为乱码。
把rule.json文件重建后也不行。编辑器是npp
