### ISSUE TITLE
【添加】

### ISSUE THREAD

**Issue by 990721830** [dengyuhan/magnetW#6]
cntorrentkitty.com
feijibt.org

**Comment by 990721830** [comment]
还有网站后面加%s到底行不行啊...
我想要配合拖拽软件啊
要是可以的话把搜索

串给我惹

**Comment by dengyuhan** [comment]
啥意思。。。

**Comment by 990721830** [comment]
1.比如github搜索我字

2.得到https://github.com/search?utf8=✓&q=我&type=
把我改成%s 就可以加入自定义引擎了

3.https://github.com/search?utf8=✓&q=%s&type=

4.http://bt.xiandan.in你网站搜索后是没有的
我应该怎么找到这个搜索串是什么

**Comment by dengyuhan** [comment]
不支持，建议自行实现发布到自己的服务器

**Comment by 990721830** [comment]
嘤嘤嘤...
我可是一个小白惹...

**Comment by 990721830** [comment]
你不会弄喵?
